services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - ./frontend:/app

  backend:
    build:
      context: ./backend
    ports:
      - "3002:3002"
    networks:
      - app-network
    volumes:
      - ./backend:/app

networks:
  app-network:
    driver: bridge
